"""2024-02-04_Add session tables

Revision ID: 14f1243e001a
Revises: 2c85cbc811fa
Create Date: 2024-02-04 19:44:16.623001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f1243e001a'
down_revision: Union[str, None] = '2c85cbc811fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True, foreign_key='users.id'),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('is_series', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_table('session_games',
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], )
    )
    op.create_table('session_picks',
    sa.Column('pick_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pick_id'], ['picks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], )
    )
    op.create_foreign_key(None, 'picks', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'picks', type_='foreignkey')
    op.drop_table('session_picks')
    op.drop_table('session_games')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
