"""2024-02-05_Add backrefS

Revision ID: 1be52c36b1ce
Revises: cbdb84600ed0
Create Date: 2024-02-05 10:59:29.675596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1be52c36b1ce'
down_revision: Union[str, None] = 'cbdb84600ed0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
