"""2024-02-01_Add marquee games

Revision ID: 2c85cbc811fa
Revises: 6b13cf211689
Create Date: 2024-02-01 15:40:15.966030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c85cbc811fa'
down_revision: Union[str, None] = '6b13cf211689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_marquee', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_marquee')
    # ### end Alembic commands ###
