
"""2024-01-27_

Revision ID: 63f204419699
Revises: b480dace1f38
Create Date: 2024-01-27 12:54:40.093113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f204419699'
down_revision: Union[str, None] = 'b480dace1f38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id', sa.String(), nullable=False))
    op.add_column('users', sa.Column('favoriteTeam', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('selectionTiming', sa.String(), nullable=False))
    op.drop_index('ix_users_uid', table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_foreign_key(None, 'users', 'teams', ['favoriteTeam'], ['id'])
    op.drop_column('users', 'email')
    op.drop_column('users', 'uid')
    op.drop_column('users', 'imageURL')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('imageURL', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('uid', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index('ix_users_uid', 'users', ['uid'], unique=False)
    op.drop_column('users', 'selectionTiming')
    op.drop_column('users', 'favoriteTeam')
    op.drop_column('users', 'id')
    # ### end Alembic commands ###
