"""2024-02-08_Add series field for picks

Revision ID: 9902ad55b787
Revises: 1be52c36b1ce
Create Date: 2024-02-08 10:43:39.141326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9902ad55b787'
down_revision: Union[str, None] = '1be52c36b1ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('is_series', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picks', 'is_series')
    # ### end Alembic commands ###
