"""2024-03-04_

Revision ID: c5f25edc7966
Revises: ef73b4eefb0a
Create Date: 2024-03-04 21:15:35.731626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5f25edc7966'
down_revision: Union[str, None] = 'ef73b4eefb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('picks', sa.Column('correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('picks', 'correct')
    # ### end Alembic commands ###
