"""2024-02-04_Add session tables (add foreign key mistake, stupid copilot)

Revision ID: cbdb84600ed0
Revises: 14f1243e001a
Create Date: 2024-02-04 19:45:15.730872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbdb84600ed0'
down_revision: Union[str, None] = '14f1243e001a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'sessions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    # ### end Alembic commands ###
