"""2024-02-08_Add unique constraint for picks

Revision ID: d14ab32aed06
Revises: 9902ad55b787
Create Date: 2024-02-08 11:26:47.947554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd14ab32aed06'
down_revision: Union[str, None] = '9902ad55b787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
