"""2024-02-29_winner_props

Revision ID: ef73b4eefb0a
Revises: 87ef3a06a341
Create Date: 2024-02-29 16:25:25.636038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef73b4eefb0a'
down_revision: Union[str, None] = '87ef3a06a341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('winner', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('home_score', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('away_score', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'games', 'teams', ['winner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.drop_column('games', 'away_score')
    op.drop_column('games', 'home_score')
    op.drop_column('games', 'winner')
    # ### end Alembic commands ###
