"""2024-03-28_Catchup

Revision ID: f06b1ea5ba44
Revises: c5f25edc7966
Create Date: 2024-03-28 21:22:52.812457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f06b1ea5ba44'
down_revision: Union[str, None] = 'c5f25edc7966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
