"""2023-12-11_

Revision ID: 22611f22019e
Revises: c4a570ec9009
Create Date: 2023-12-11 21:15:29.825158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22611f22019e'
down_revision: Union[str, None] = 'c4a570ec9009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('cityName', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('teamName', sa.String(), nullable=True))
    op.add_column('teams', sa.Column('abbr', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'abbr')
    op.drop_column('teams', 'teamName')
    op.drop_column('teams', 'cityName')
    # ### end Alembic commands ###
