"""2023-12-12_Change start time to datetime (UTC)

Revision ID: 494bbca7206f
Revises: 50b511c1f92e
Create Date: 2023-12-12 00:02:23.486973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '494bbca7206f'
down_revision: Union[str, None] = '50b511c1f92e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('games', sa.Column('startTimeUTC', sa.DateTime(), nullable=True))
    op.add_column('games', sa.Column('venue', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'venue')
    op.drop_column('games', 'startTimeUTC')
    op.drop_column('games', 'date')
    # ### end Alembic commands ###
