"""2023-12-18_Add series numbers

Revision ID: 4eecfe1ccadb
Revises: 6ed6f657e2de
Create Date: 2023-12-18 16:09:13.615548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eecfe1ccadb'
down_revision: Union[str, None] = '6ed6f657e2de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('series_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'series_num')
    # ### end Alembic commands ###
