name: Deploy Docker - Dev

on:
  push:
    branches:
      - dev

  workflow_dispatch:
    inputs:
      version:
        description: 'Docker image version'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to repo
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{steps.meta.outputs.tags}}
          labels: ${{steps.meta.outputs.labels}}

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build_and_push
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      - name: Log in to repo
#        uses: docker/login-action@v3
#        with:
#          registry: ${{env.REGISTRY}}
#          username: ${{github.actor}}
#          password: ${{secrets.GITHUB_TOKEN}}
#
#      - name: Pull image
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{secrets.DROPLET_IP}}
#          username: root # this is generally dangerous, please modify this in the future
#          key: ${{secrets.DROPLET_SSH_KEY}}
#          script: |
#            docker run ${{env.REGISTRY}}/${{env.USERNAME}}:latest